---
name: Build

on: pull_request

jobs:
  build:
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@1.5.6
    with:
      tag: latest-actions-build
      repo: freezing-nq
    secrets: inherit
