---
name: Build

on: pull_request

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    uses: freezingsaddles/freezing-web/.github/workflows/build-docker.yml@fc58c1c4339013a6dc952fbc28e0e573b8a37698 # harden-workflows, pending 1.7.0
    with:
      tag: latest-actions-build
      repo: freezing-nq
      push: false
