---
name: Lint

on: pull_request

permissions:
  contents: read

jobs:

  # Thanks https://black.readthedocs.io/en/stable/integrations/github_actions.html
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python environment
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
      - name: black Lint
        uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # 26.5.1
      - name: isort Lint
        uses: isort/isort-action@24d8a7a51d33ca7f36c3f23598dafa33f7071326 # v1
      - name: flake8 Lint
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba # v2
