---
name: Test

on: pull_request

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          pip install . -e '.[dev]'
      - name: Run pytest
        run: pytest
